dist: xenial
install:
# Install Go ...
- rm -r /home/travis/.gimme/versions/go1.7.4.linux.amd64
- wget https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz
- tar xf go1.8.linux-amd64.tar.gz
- sudo mv go /usr/local
- mkdir -p $HOME/go/src
# Set environment variables ...
- export GOROOT=/usr/local/go
- export GOPATH=$HOME/go
- export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
# Install Go packages ...
- wget https://s3-us-west-2.amazonaws.com/gx-deps/gx.zip
- unzip gx.zip -d $GOPATH/src
- go get github.com/enzoh/go-logging
- go get github.com/hashicorp/golang-lru
- go get github.com/dfinity/go-revolver/artifact
- go get github.com/dfinity/go-revolver/streamstore
- go get github.com/dfinity/go-revolver/util
script:
- pushd p2p
- go test
- popd
